### ISSUE TITLE
Debug j.mp usage

### ISSUE THREAD

**Issue by impredicative** [brandonrobertz/AcademicUrlTitles#2]
Here is an example of a random non-use of j.mp on 2019-01-30 for the KDnuggets feed in ##machinelearning:
> <KDnuggets> Random forests explained intuitively | https://www.kdnuggets.com/2019/01/random-forests-explained-intuitively.html

It's unclear why j.mp didn't work for this example.

**Comment by brandonrobertz** [comment]
Fixed. This was a config issue. We're regexing all non-arXiv feeds for shortening.
